services:
    web:
        image: therros1992/demo-app-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/demo-app/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: therros1992/demo-app-web
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
           - db_root_password
secrets:
    db_root_password:
        external: true  
networks:
    app-network:
